//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicational_practice.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals_Gordeeva
    {
        public Nullable<int> id_animals_gordeeva { get; set; }
        public string name { get; set; }
        public string detachment { get; set; }
    }
}
