//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicational_practice.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int id_country { get; set; }
        public string name { get; set; }
        public string capital { get; set; }
        public int square { get; set; }
        public int population { get; set; }
        public string continent { get; set; }
    }
}
