//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicational_practice.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int id_exam { get; set; }
        public System.DateTime date_exam { get; set; }
        public Nullable<int> code_discipline { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string auditorium { get; set; }
        public int mark { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
