//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicational_practice.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head_of_the_Department
    {
        public int id_head { get; set; }
        public int experience { get; set; }
    }
}
