//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicational_practice.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Edicational_practice_321Entities1 : DbContext
    {
        public Edicational_practice_321Entities1()
            : base("name=Edicational_practice_321Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Countries_Gordeeva> Countries_Gordeeva { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Head_of_the_Department> Head_of_the_Department { get; set; }
        public virtual DbSet<Learners> Learners { get; set; }
        public virtual DbSet<Management_Gordeeva> Management_Gordeeva { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Animals_Gordeeva> Animals_Gordeeva { get; set; }
        public virtual DbSet<Flowers_Gordeeva> Flowers_Gordeeva { get; set; }
        public virtual DbSet<Gymnasium_students> Gymnasium_students { get; set; }
    }
}
